### PR TITLE
Add french locale

### PR DESCRIPTION
**Pull request by GuillaumeOcculy**

### CODE REVIEW

**Comment by philipgiuliani** [comment]
@kritik I noticed that all other locales added until now were not added in the [validate_url.rb](https://github.com/perfectline/validates_url/blob/master/lib/validate_url.rb#L4) file! Isn't it enough to just add the locale folder to the load_path?

**Comment by ldonnet** [comment]
:+1: It will be great to add locales automatically when you merge locales

**Comment by kritik** [comment]
I totally agree, but can you update pull request? Currently it has conflicts. Once it has no conflicts - I'll merge it

**Comment by GuillaumeOcculy** [comment]
It's up to date :)

**Comment by ldonnet** [comment]
@GuillaumeOcculy Thanks!

**Comment by kritik** [comment]
done, thank you

**Pull request merged**
